version: '3.8'
services:
    # Add other services here
    app:
        build:
            context: .
            target: prod
        logging:
            options:
                max-size: "10m"
                max-file: "3"
                compress: "true"
                labels: inversify-graphql-example
        # This reads from .env file
        environment:
            - NODE_ENV=production
            - PORT=$PORT
            - GRAPHQL_DEPTH_LIMIT=$GRAPHQL_DEPTH_LIMIT
        ports: 
            - "8080:80"